<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dCMS.Reports.Worker</RootNamespace>
    <UserSecretsId>dCMS-Reports-Worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="dbup-postgresql" Version="5.0.40" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dCMS.Infrastructure\dCMS.Infrastructure.csproj" />
    <ProjectReference Include="..\dCMS.Messaging.Contracts\dCMS.Messaging.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

</Project>

