<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>dCMS.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dCMS.Messaging.Contracts\dCMS.Messaging.Contracts.csproj" />
  </ItemGroup>

</Project>
