FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/backend ./src/backend
WORKDIR /src/src/backend

RUN dotnet restore dCMS.Reports.Worker/dCMS.Reports.Worker.csproj
RUN dotnet publish dCMS.Reports.Worker/dCMS.Reports.Worker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "dCMS.Reports.Worker.dll"]

