/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background:                  "rgb(255 248 247 / <alpha-value>)",
        surface:                     "rgb(255 248 247 / <alpha-value>)",
        "surface-bright":            "rgb(255 248 247 / <alpha-value>)",
        "surface-container-lowest":  "rgb(255 255 255 / <alpha-value>)",
        "surface-container-low":     "rgb(255 240 239 / <alpha-value>)",
        "surface-container":         "rgb(255 233 231 / <alpha-value>)",
        "surface-container-high":    "rgb(255 226 222 / <alpha-value>)",
        "surface-container-highest": "rgb(255 218 214 / <alpha-value>)",
        "surface-variant":           "rgb(251 219 216 / <alpha-value>)",
        "on-background":             "rgb(40 23 22 / <alpha-value>)",
        "on-surface":                "rgb(40 23 22 / <alpha-value>)",
        "on-surface-variant":        "rgb(92 64 61 / <alpha-value>)",
        primary:                     "rgb(170 0 20 / <alpha-value>)",
        "primary-container":         "rgb(209 32 38 / <alpha-value>)",
        "primary-fixed":             "rgb(255 218 214 / <alpha-value>)",
        "on-primary":                "rgb(255 255 255 / <alpha-value>)",
        "on-primary-container":      "rgb(255 255 255 / <alpha-value>)",
        "on-primary-fixed-variant":  "rgb(114 20 20 / <alpha-value>)",
        secondary:                   "rgb(165 58 53 / <alpha-value>)",
        "secondary-container":       "rgb(254 124 115 / <alpha-value>)",
        "secondary-fixed":           "rgb(254 218 214 / <alpha-value>)",
        "on-secondary-container":    "rgb(114 20 20 / <alpha-value>)",
        "on-secondary-fixed-variant":"rgb(92 20 18 / <alpha-value>)",
        tertiary:                    "rgb(0 88 128 / <alpha-value>)",
        "tertiary-container":        "rgb(0 114 163 / <alpha-value>)",
        "on-tertiary-container":     "rgb(255 255 255 / <alpha-value>)",
        outline:                     "rgb(145 111 108 / <alpha-value>)",
        "outline-variant":           "rgb(229 189 185 / <alpha-value>)",
        error:                       "rgb(186 26 26 / <alpha-value>)",
        "error-container":           "rgb(255 218 214 / <alpha-value>)",
        "on-error-container":        "rgb(147 0 10 / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
