<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dCMS.Inventory.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dCMS.AspNetCore.Auth\dCMS.AspNetCore.Auth.csproj" />
    <ProjectReference Include="..\dCMS.Common\dCMS.Common.csproj" />
    <ProjectReference Include="..\dCMS.Catalog.Domain\dCMS.Catalog.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Infrastructure\dCMS.Infrastructure.csproj" />
    <ProjectReference Include="..\dCMS.Inventory.Infrastructure\dCMS.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\dCMS.Inventory.Core\dCMS.Inventory.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
  </ItemGroup>

</Project>
