<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\dCMS.Common\dCMS.Common.csproj" />
    <ProjectReference Include="..\dCMS.Catalog.Domain\dCMS.Catalog.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Promotions.Domain\dCMS.Promotions.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Fulfillment.Domain\dCMS.Fulfillment.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Approvals.Domain\dCMS.Approvals.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Imports.Domain\dCMS.Imports.Domain.csproj" />
    <ProjectReference Include="..\dCMS.Messaging.Contracts\dCMS.Messaging.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.0" />
    <PackageReference Include="dbup-postgresql" Version="5.0.40" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.10" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

</Project>
