using Microsoft.Data.SqlClient;

namespace dCMS.Tools.SpawnTenant.Steps;

public sealed class WriteEnvFileStep : IProvisioningStep
{
    public string Name => ProvisioningStepNames.WriteEnvFile;
    public int Order => 4;
    public int MaxRetries => 1;

    public async Task ExecuteAsync(ProvisioningContext ctx)
    {
        if (ctx.IsStepCompleted(Name))
            return;

        var tenantConn = BuildTenantConnectionString(ctx.SqlServerSaConnectionString, ctx.UmbracoDbName);
        Directory.CreateDirectory(Path.GetDirectoryName(ctx.EnvFilePath)!);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"# Generated by SpawnTenant for tenant={ctx.TenantId}");
        sb.AppendLine($"# Do NOT commit this file — it contains the unattended admin password.");
        sb.AppendLine();
        sb.AppendLine($"DCMS_TENANT_ID={ctx.TenantId}");
        sb.AppendLine($"ConnectionStrings__umbracoDbDSN={tenantConn}");
        sb.AppendLine($"ConnectionStrings__umbracoDbDSN_ProviderName=Microsoft.Data.SqlClient");
        sb.AppendLine();
        sb.AppendLine($"Umbraco__CMS__Unattended__InstallUnattended=true");
        sb.AppendLine($"Umbraco__CMS__Unattended__UnattendedUserName={ctx.TenantId} admin");
        sb.AppendLine($"Umbraco__CMS__Unattended__UnattendedUserEmail={ctx.AdminEmail}");
        sb.AppendLine($"Umbraco__CMS__Unattended__UnattendedUserPassword={ctx.AdminPassword}");
        sb.AppendLine();
        sb.AppendLine($"uSync__Settings__RootFolder=~/uSync/v16/");
        sb.AppendLine($"uSync__Settings__ImportAtStartup=All");
        sb.AppendLine($"uSync__Settings__ExportAtStartup=None");
        sb.AppendLine($"uSync__Settings__ExportOnSave=None");

        await File.WriteAllTextAsync(ctx.EnvFilePath, sb.ToString(), ctx.CancellationToken).ConfigureAwait(false);
        ctx.StepArtifacts["env_file_written"] = true;
        ctx.MarkStepCompleted(Name);
    }

    public Task RollbackAsync(ProvisioningContext ctx)
    {
        if (ctx.StepArtifacts.TryGetValue("env_file_written", out var written) && written is true &&
            File.Exists(ctx.EnvFilePath))
        {
            File.Delete(ctx.EnvFilePath);
        }
        return Task.CompletedTask;
    }

    internal static string BuildTenantConnectionString(string saConn, string dbName)
    {
        var b = new SqlConnectionStringBuilder(saConn) { InitialCatalog = dbName };
        return b.ConnectionString;
    }
}
