<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dCMS.Catalog.Worker</RootNamespace>
    <UserSecretsId>dCMS-Catalog-Worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.401" />
    <PackageReference Include="ClosedXML" Version="0.104.*" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MassTransit" Version="8.3.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dCMS.Infrastructure\dCMS.Infrastructure.csproj" />
    <ProjectReference Include="..\dCMS.Common\dCMS.Common.csproj" />
    <ProjectReference Include="..\dCMS.Catalog.Domain\dCMS.Catalog.Domain.csproj" />
  </ItemGroup>

</Project>
