import { useMemo } from "react";
import { DataTable } from "../components/DataTable";
import { IconDownload } from "../icons";
import { createOrderColumns } from "../orders-columns";
import { exportOrderProcessingFile } from "../exportOrders";
import type { Order } from "../types";

// ── Mock data ─────────────────────────────────────────────────────────────────
// Replace with API call when backend is wired.
const MOCK_ORDERS: Order[] = [
  {
    doNumber: "DO-2024-001",
    orderId: "ORD-998122",
    orderDate: "24 May 2024",
    type: "Retail",
    customerName: "Michael Vance",
    customerEmail: "m.vance@example.com",
    customerContactNo: "+44 7911 123456",
    status: "Open Order",
    fulfilledDate: null,
    deliveryDate: "27 May 2024",
    deliveryOption: "Standard",
    shippingStatus: "Pending",
    processingOfficer: "Alice Tan",
    tags: "VIP",
    paymentGateway: "Stripe",
    store: "London Central",
    storeAutoId: "STR-001",
    distributionCentre: "DC-North",
    paymentMethod: "Credit Card",
    paymentDate: "24 May 2024",
    shippingAddressLine1: "12 Baker Street",
    shippingAddressLine2: "Flat 3B",
    shippingPostalCode: "NW1 6XE",
    shippingCountry: "GB",
    billingAddressLine1: "12 Baker Street",
    billingAddressLine2: "Flat 3B",
    billingPostalCode: "NW1 6XE",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-002",
    orderId: "ORD-998123",
    orderDate: "24 May 2024",
    type: "Wholesale",
    customerName: "Sarah Connor",
    customerEmail: "s.connor@sky.net",
    customerContactNo: "+49 30 12345678",
    status: "Delivered",
    fulfilledDate: "25 May 2024",
    deliveryDate: "25 May 2024",
    deliveryOption: "Express",
    shippingStatus: "Delivered",
    processingOfficer: "Ben Müller",
    tags: "Wholesale,Priority",
    paymentGateway: "PayPal",
    store: "Berlin Hub",
    storeAutoId: "STR-002",
    distributionCentre: "DC-Central",
    paymentMethod: "Multi Payment",
    paymentDate: "24 May 2024",
    shippingAddressLine1: "Unter den Linden 5",
    shippingAddressLine2: null,
    shippingPostalCode: "10117",
    shippingCountry: "DE",
    billingAddressLine1: "Friedrichstr. 100",
    billingAddressLine2: "3. OG",
    billingPostalCode: "10117",
    billingCountry: "DE",
  },
  {
    doNumber: "DO-2024-003",
    orderId: "ORD-998124",
    orderDate: "23 May 2024",
    type: "Online",
    customerName: "James Bond",
    customerEmail: "007@mi6.gov",
    customerContactNo: "+44 20 7946 0007",
    status: "Processing",
    fulfilledDate: null,
    deliveryDate: "28 May 2024",
    deliveryOption: "Standard",
    shippingStatus: "Pending",
    processingOfficer: "Alice Tan",
    tags: null,
    paymentGateway: "Stripe",
    store: "Global Online",
    storeAutoId: "STR-003",
    distributionCentre: "DC-South",
    paymentMethod: "Bank Transfer",
    paymentDate: "23 May 2024",
    shippingAddressLine1: "85 Albert Embankment",
    shippingAddressLine2: null,
    shippingPostalCode: "SE1 7TP",
    shippingCountry: "GB",
    billingAddressLine1: "85 Albert Embankment",
    billingAddressLine2: null,
    billingPostalCode: "SE1 7TP",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-004",
    orderId: "ORD-998125",
    orderDate: "22 May 2024",
    type: "Retail",
    customerName: "Ada Lovelace",
    customerEmail: "ada@babbage.io",
    customerContactNo: "+44 7700 900123",
    status: "Ready for Delivery",
    fulfilledDate: null,
    deliveryDate: "26 May 2024",
    deliveryOption: "Express",
    shippingStatus: "Shipped",
    processingOfficer: "Charlie Ng",
    tags: "New Customer",
    paymentGateway: "Stripe",
    store: "London Central",
    storeAutoId: "STR-001",
    distributionCentre: "DC-North",
    paymentMethod: "Credit Card",
    paymentDate: "22 May 2024",
    shippingAddressLine1: "10 St James's Square",
    shippingAddressLine2: null,
    shippingPostalCode: "SW1Y 4LE",
    shippingCountry: "GB",
    billingAddressLine1: "10 St James's Square",
    billingAddressLine2: null,
    billingPostalCode: "SW1Y 4LE",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-005",
    orderId: "ORD-998126",
    orderDate: "22 May 2024",
    type: "Online",
    customerName: "Alan Turing",
    customerEmail: "alan@enigma.uk",
    customerContactNo: "+44 7911 654321",
    status: "Returned",
    fulfilledDate: "24 May 2024",
    deliveryDate: "23 May 2024",
    deliveryOption: "Same Day",
    shippingStatus: "Returned",
    processingOfficer: "Diana Park",
    tags: "Returned",
    paymentGateway: "PayPal",
    store: "Global Online",
    storeAutoId: "STR-003",
    distributionCentre: "DC-East",
    paymentMethod: "E-Wallet",
    paymentDate: "22 May 2024",
    shippingAddressLine1: "Bletchley Park",
    shippingAddressLine2: "Block H",
    shippingPostalCode: "MK3 6EB",
    shippingCountry: "GB",
    billingAddressLine1: "Bletchley Park",
    billingAddressLine2: "Block H",
    billingPostalCode: "MK3 6EB",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-006",
    orderId: "ORD-998127",
    orderDate: "21 May 2024",
    type: "Wholesale",
    customerName: "Grace Hopper",
    customerEmail: "grace@navy.mil",
    customerContactNo: "+1 202 555 0143",
    status: "Partially Fulfilled",
    fulfilledDate: null,
    deliveryDate: "30 May 2024",
    deliveryOption: "Standard",
    shippingStatus: "Shipped",
    processingOfficer: "Ben Müller",
    tags: "Wholesale,Partial",
    paymentGateway: "Adyen",
    store: "Berlin Hub",
    storeAutoId: "STR-002",
    distributionCentre: "DC-West",
    paymentMethod: "Multi Payment",
    paymentDate: "21 May 2024",
    shippingAddressLine1: "Pentagon, Arlington",
    shippingAddressLine2: null,
    shippingPostalCode: "22201",
    shippingCountry: "US",
    billingAddressLine1: "Pentagon, Arlington",
    billingAddressLine2: null,
    billingPostalCode: "22201",
    billingCountry: "US",
  },
  {
    doNumber: "DO-2024-007",
    orderId: "ORD-998128",
    orderDate: "20 May 2024",
    type: "Retail",
    customerName: "Nikola Tesla",
    customerEmail: "nikola@ac-dc.com",
    customerContactNo: "+1 212 555 0187",
    status: "Admin Cancelled",
    fulfilledDate: null,
    deliveryDate: null,
    deliveryOption: null,
    shippingStatus: null,
    processingOfficer: "Charlie Ng",
    tags: "Cancelled",
    paymentGateway: "Stripe",
    store: "Paris Flagship",
    storeAutoId: "STR-004",
    distributionCentre: undefined,
    paymentMethod: "Credit Card",
    paymentDate: "20 May 2024",
    shippingAddressLine1: "5 Avenue Anatole France",
    shippingAddressLine2: null,
    shippingPostalCode: "75007",
    shippingCountry: "FR",
    billingAddressLine1: "5 Avenue Anatole France",
    billingAddressLine2: null,
    billingPostalCode: "75007",
    billingCountry: "FR",
  },
  {
    doNumber: "DO-2024-008",
    orderId: "ORD-998129",
    orderDate: "20 May 2024",
    type: "Online",
    customerName: "Marie Curie",
    customerEmail: "marie@radium.fr",
    customerContactNo: "+33 1 23 45 67 89",
    status: "Picked Up",
    fulfilledDate: "21 May 2024",
    deliveryDate: "21 May 2024",
    deliveryOption: "Click & Collect",
    shippingStatus: "Delivered",
    processingOfficer: "Diana Park",
    tags: null,
    paymentGateway: "PayPal",
    store: "Paris Flagship",
    storeAutoId: "STR-004",
    distributionCentre: "DC-Central",
    paymentMethod: "Bank Transfer",
    paymentDate: "20 May 2024",
    shippingAddressLine1: "Paris Flagship Store",
    shippingAddressLine2: "1 Rue de Rivoli",
    shippingPostalCode: "75001",
    shippingCountry: "FR",
    billingAddressLine1: "36 Quai de Béthune",
    billingAddressLine2: null,
    billingPostalCode: "75004",
    billingCountry: "FR",
  },
  {
    doNumber: "DO-2024-009",
    orderId: "ORD-998130",
    orderDate: "19 May 2024",
    type: "Retail",
    customerName: "Isaac Newton",
    customerEmail: "isaac@apple.science",
    customerContactNo: "+44 1223 337733",
    status: "Out for Delivery",
    fulfilledDate: null,
    deliveryDate: "19 May 2024",
    deliveryOption: "Same Day",
    shippingStatus: "Out for Delivery",
    processingOfficer: "Alice Tan",
    tags: null,
    paymentGateway: "Stripe",
    store: "London Central",
    storeAutoId: "STR-001",
    distributionCentre: "DC-North",
    paymentMethod: "Credit Card",
    paymentDate: "19 May 2024",
    shippingAddressLine1: "Trinity College",
    shippingAddressLine2: "Trinity Street",
    shippingPostalCode: "CB2 1TQ",
    shippingCountry: "GB",
    billingAddressLine1: "Trinity College",
    billingAddressLine2: "Trinity Street",
    billingPostalCode: "CB2 1TQ",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-010",
    orderId: "ORD-998131",
    orderDate: "18 May 2024",
    type: "Wholesale",
    customerName: "Linus Torvalds",
    customerEmail: "linus@kernel.org",
    customerContactNo: "+358 9 123 4567",
    status: "Open Order",
    fulfilledDate: null,
    deliveryDate: "25 May 2024",
    deliveryOption: "Standard",
    shippingStatus: "Pending",
    processingOfficer: "Erik Lindqvist",
    tags: "Wholesale",
    paymentGateway: "Adyen",
    store: "Helsinki Store",
    storeAutoId: "STR-005",
    distributionCentre: "DC-North",
    paymentMethod: "Bank Transfer",
    paymentDate: "18 May 2024",
    shippingAddressLine1: "Leppävaara 1",
    shippingAddressLine2: null,
    shippingPostalCode: "02600",
    shippingCountry: "FI",
    billingAddressLine1: "Leppävaara 1",
    billingAddressLine2: null,
    billingPostalCode: "02600",
    billingCountry: "FI",
  },
  {
    doNumber: "DO-2024-011",
    orderId: "ORD-998132",
    orderDate: "17 May 2024",
    type: "Online",
    customerName: "Tim Berners-Lee",
    customerEmail: "tim@w3.org",
    customerContactNo: "+44 7700 900456",
    status: "Delivered",
    fulfilledDate: "19 May 2024",
    deliveryDate: "19 May 2024",
    deliveryOption: "Express",
    shippingStatus: "Delivered",
    processingOfficer: "Alice Tan",
    tags: null,
    paymentGateway: "PayPal",
    store: "Global Online",
    storeAutoId: "STR-003",
    distributionCentre: undefined,
    paymentMethod: "Multi Payment",
    paymentDate: "17 May 2024",
    shippingAddressLine1: "76 Chancery Lane",
    shippingAddressLine2: null,
    shippingPostalCode: "WC2A 1AA",
    shippingCountry: "GB",
    billingAddressLine1: "76 Chancery Lane",
    billingAddressLine2: null,
    billingPostalCode: "WC2A 1AA",
    billingCountry: "GB",
  },
  {
    doNumber: "DO-2024-012",
    orderId: "ORD-998133",
    orderDate: "16 May 2024",
    type: "Retail",
    customerName: "Edsger Dijkstra",
    customerEmail: "edsger@graph.nl",
    customerContactNo: "+31 20 123 4567",
    status: "Ready for Pickup",
    fulfilledDate: null,
    deliveryDate: "18 May 2024",
    deliveryOption: "Click & Collect",
    shippingStatus: "Shipped",
    processingOfficer: "Charlie Ng",
    tags: null,
    paymentGateway: "Stripe",
    store: "Amsterdam Central",
    storeAutoId: "STR-006",
    distributionCentre: "DC-West",
    paymentMethod: "Credit Card",
    paymentDate: "16 May 2024",
    shippingAddressLine1: "Amsterdam Central Store",
    shippingAddressLine2: "Dam 1",
    shippingPostalCode: "1012 JS",
    shippingCountry: "NL",
    billingAddressLine1: "Herengracht 282",
    billingAddressLine2: null,
    billingPostalCode: "1016 BX",
    billingCountry: "NL",
  },
];

// ─────────────────────────────────────────────────────────────────────────────

type Props = {
  onViewOrder?: (orderId: string) => void;
  onTakeAction?: (orderId: string) => void;
};

export function OrderProcessingPage({ onViewOrder, onTakeAction }: Props) {
  const columns = useMemo(
    () => createOrderColumns(onViewOrder, onTakeAction),
    [onViewOrder, onTakeAction]
  );

  return (
    <>
      {/* Page header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <nav className="flex text-[10px] uppercase tracking-widest text-on-surface-variant font-bold mb-1">
            <span>Orders</span>
            <span className="mx-2">/</span>
            <span className="text-primary">Order Processing</span>
          </nav>
          <h1 className="text-2xl font-bold tracking-tight text-on-surface font-headline">
            Order Processing
          </h1>
          <p className="text-sm text-on-surface-variant mt-1">
            Manage and track your end-to-end order lifecycle
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            type="button"
            className="px-4 py-2 text-sm font-medium text-on-surface hover:bg-surface-container-high transition-colors rounded-lg flex items-center gap-2"
            onClick={() => exportOrderProcessingFile(MOCK_ORDERS)}
          >
            <IconDownload />
            Export
          </button>
        </div>
      </div>

      <DataTable
        columns={columns}
        data={MOCK_ORDERS}
        defaultHiddenColumns={["distributionCentre", "paymentMethod", "paymentDate"]}
        globalFilterPlaceholder="Search by order, customer, store…"
      />
    </>
  );
}
