-- DAI-319 — full OrderSagaState row shape for MassTransit.EntityFrameworkCore saga repository (PostgreSQL).
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "OrderId" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "TenantId" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "StoreId" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "CustomerId" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "TotalAmount" NUMERIC(18, 2) NOT NULL DEFAULT 0;
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "Currency" VARCHAR(16) NOT NULL DEFAULT '';
ALTER TABLE "OrderSagaState" ADD COLUMN IF NOT EXISTS "ReserveLines" JSONB NOT NULL DEFAULT '[]'::jsonb;
